### ISSUE TITLE
Service Release: [Spellcheck] [v0.2.2]

### ISSUE THREAD

**Issue by SeanKilleen** [AWiderDotNET/mutual-aid#10]
# Service Release: `Spellcheck` `v0.2.2`

* Release Link: https://github.com/AWiderDotNET/service-spellcheck/releases/tag/v0.2.2

## Notes

____

## Prerequisite Tasks

- [x] A release exists in my service's repo and I've added it in the above markdown

### If Releasing for the first time

- [x] Add a `service:[servicename]` label in this repository.

### Tasks for Every Release
- [x] Add/Update this repo's `ServiceCatalog.md` as applicable
- [x] Add/Update your service templates in the `.github/ISSUE_TEMPLATE/config.yml` file here.
- [x] Add/Update your service's templates in the `.github/ISSUE_TEMPLATE/` directory here.
- [x] Find incomplete applications of the service in [the issues](https://github.com/AWiderDotNET/mutual-aid/issues), and note in them that a new release has occurred.
